### ISSUE TITLE
Images get ALT of "undefined"

### ISSUE THREAD

**Issue by twoixter** [marketgoo/Ola-Emails#3]
Renderd `<img>` tags gets ALT tag value of `undefined`. See attached capture:

![Captura de pantalla 2020-04-23 a las 1 30 31](https://user-images.githubusercontent.com/88262/80043499-29723200-8502-11ea-827e-004190ad2295.png)

MJML code for the above was:

```html
<ola-footer-address src="{{ img_asset_url("logo-gray.png", true) }}">
    ... some text ...
</ola-footer-address>
```

**Comment by oscarotero** [comment]
Fixed in #4
